### ISSUE TITLE
Ustream SDK update. How to update on wordpress

### ISSUE THREAD

**Issue by fdamoed** [hoyce/ustream-for-wordpress#6]
Hi Niklas,

I spoke to you before on Wordpress comments. We at Paso Pacifico, an environmental non-profit, are using Ustream for live streaming of sea turtle events for education purposes. 

It seems like the videos are playing in the Android application, but not on the Wordpress website. We keep getting error messages, and the video box takes us to Ustream channel when we click play. We want to have streaming directly on our page (turtlefriend.org). I was told that Ustream has updated on their side. Could you help us on applying these changes on our side? Would like to share more information on private.

Thanks in advance,
Felipe

**Comment by hoyce** [comment]
Hi Felipe!
Thanks for getting back to me. How does your tag look like when you use it in the page?
I tried this tag on my blog and it works just fine: 
`[embed]https://www.ustream.tv/recorded/80100669[/embed]`
or this for live stream:
`[embed]http://www.ustream.tv/channel/ve4mWw4aQN6[/embed]`

The videos are shown here: https://www.hoyce.com/wordpress-plugins/

Best regards, 
Niklas

**Comment by hoyce** [comment]
The problem seemed to be a php configuration. Marking this issue resolved.
